/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaraunt;

//import java.awt.CardLayout;

/**
 *
 * @author trims
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }
    
    double ids[] = {1289, 1863, 8246, 7979};            //stores an array of acceptable id numbers for login

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        Order = new javax.swing.JPanel();
        dynamicPanel = new javax.swing.JPanel();
        orderPanel = new javax.swing.JPanel();
        currentOrder = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        appetizers = new javax.swing.JPanel();
        appList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        salads = new javax.swing.JPanel();
        saladList = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        sandwiches = new javax.swing.JPanel();
        sandList = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        entrees = new javax.swing.JPanel();
        entreeList = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        desserts = new javax.swing.JPanel();
        dessertList = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        drinks = new javax.swing.JPanel();
        drinkList = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        allergies = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        upcharge = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        noUpcharge = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        btnApps = new javax.swing.JButton();
        btnSalad = new javax.swing.JButton();
        btnSandwich = new javax.swing.JButton();
        btnEntree = new javax.swing.JButton();
        btnDessert = new javax.swing.JButton();
        btnDrinks = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnAddNoCharge = new javax.swing.JButton();
        btnAddCharge = new javax.swing.JButton();
        btnAllergy = new javax.swing.JButton();
        btnVoid = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        s1 = new javax.swing.JToggleButton();
        s2 = new javax.swing.JToggleButton();
        s3 = new javax.swing.JToggleButton();
        s4 = new javax.swing.JToggleButton();
        Tables = new javax.swing.JPanel();
        tbl10 = new javax.swing.JButton();
        tbl20 = new javax.swing.JButton();
        tbl30 = new javax.swing.JButton();
        tbl40 = new javax.swing.JButton();
        tbl50 = new javax.swing.JButton();
        tbl60 = new javax.swing.JButton();
        tbl61 = new javax.swing.JButton();
        newTable = new javax.swing.JButton();
        report = new javax.swing.JButton();
        exitTables = new javax.swing.JButton();
        Payment = new javax.swing.JPanel();
        seatPayment = new javax.swing.JPanel();
        Pay = new javax.swing.JPanel();
        emptyCash = new javax.swing.JPanel();
        creditCard = new javax.swing.JPanel();
        cardPayment = new javax.swing.JLabel();
        tipLabel = new javax.swing.JLabel();
        tipIn = new javax.swing.JTextField();
        cardAccept = new javax.swing.JButton();
        cardCancel = new javax.swing.JButton();
        cardPayIn = new javax.swing.JTextField();
        payInCash = new javax.swing.JPanel();
        totalPayment = new javax.swing.JLabel();
        changeDue = new javax.swing.JLabel();
        payIn = new javax.swing.JTextField();
        accept = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        change = new javax.swing.JLabel();
        btnCard = new javax.swing.JButton();
        btnCash = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        seat1 = new javax.swing.JToggleButton();
        seat2 = new javax.swing.JToggleButton();
        seat3 = new javax.swing.JToggleButton();
        seat4 = new javax.swing.JToggleButton();
        allSeat = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("POS"); // NOI18N

        mainPanel.setPreferredSize(new java.awt.Dimension(1300, 750));
        mainPanel.setLayout(new java.awt.CardLayout());

        login.setPreferredSize(new java.awt.Dimension(1300, 750));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOne.setText("1");
        btnOne.setPreferredSize(new java.awt.Dimension(55, 55));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        login.add(btnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        btnTwo.setText("2");
        btnTwo.setPreferredSize(new java.awt.Dimension(55, 55));
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        login.add(btnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        btnThree.setText("3");
        btnThree.setPreferredSize(new java.awt.Dimension(55, 55));
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        login.add(btnThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        btnFour.setText("4");
        btnFour.setPreferredSize(new java.awt.Dimension(55, 55));
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        login.add(btnFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        btnFive.setText("5");
        btnFive.setPreferredSize(new java.awt.Dimension(55, 55));
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        login.add(btnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        btnSix.setText("6");
        btnSix.setPreferredSize(new java.awt.Dimension(55, 55));
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        login.add(btnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        btnSeven.setText("7");
        btnSeven.setPreferredSize(new java.awt.Dimension(55, 55));
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        login.add(btnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        btnEight.setText("8");
        btnEight.setPreferredSize(new java.awt.Dimension(55, 55));
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        login.add(btnEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        btnNine.setText("9");
        btnNine.setPreferredSize(new java.awt.Dimension(55, 55));
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        login.add(btnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        btnCancel.setText("X");
        btnCancel.setPreferredSize(new java.awt.Dimension(55, 55));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        login.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        btnZero.setText("0");
        btnZero.setPreferredSize(new java.awt.Dimension(55, 55));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        login.add(btnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(55, 55));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        login.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));
        login.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 200, 30));

        mainPanel.add(login, "card5");

        Order.setPreferredSize(new java.awt.Dimension(1300, 750));
        Order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicPanel.setBackground(new java.awt.Color(0, 204, 0));
        dynamicPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(51, 51, 51)));
        dynamicPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dynamicPanel.setLayout(new java.awt.CardLayout());

        currentOrder.setViewportView(jList1);

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(currentOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        dynamicPanel.add(orderPanel, "card8");

        jList2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hot Wings\t\t\t\t\t$9.99", " ", "Southwest Chicken Spring Rolls\t\t\t$9.99", " ", "Nachos\t\t\t\t\t$9.99", " ", "Fried Pickles\t\t\t\t\t$7.99", " ", "Chips & Salsa\t\t\t\t\t$3.99", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        appList.setViewportView(jList2);

        javax.swing.GroupLayout appetizersLayout = new javax.swing.GroupLayout(appetizers);
        appetizers.setLayout(appetizersLayout);
        appetizersLayout.setHorizontalGroup(
            appetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        appetizersLayout.setVerticalGroup(
            appetizersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(appetizers, "card7");

        jList3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cobb Salad\t\t\t\t\t$12.99", " ", "Chef Salad\t\t\t\t\t$12.99", " ", "Grilled Chicken Salad\t\t\t\t$14.99", " ", "Steak Salad\t\t\t\t\t$14.99" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        saladList.setViewportView(jList3);

        javax.swing.GroupLayout saladsLayout = new javax.swing.GroupLayout(salads);
        salads.setLayout(saladsLayout);
        saladsLayout.setHorizontalGroup(
            saladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saladList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        saladsLayout.setVerticalGroup(
            saladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saladList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(salads, "card6");

        jList4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "French Dip\t\t\t\t\t$9.99", " ", "Tuna Melt\t\t\t\t\t$10.99", " ", "Steak Sandwich\t\t\t\t$14.99", " ", "Club Sandwich\t\t\t\t\t$10.99", " ", "Chicken Sandwich\t\t\t\t$9.99", " ", "Cheese Burger\t\t\t\t\t$9.99", " ", "BBQ Burger\t\t\t\t\t$10.99", " ", "Black Bean Burger\t\t\t\t$8.99" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sandList.setViewportView(jList4);

        javax.swing.GroupLayout sandwichesLayout = new javax.swing.GroupLayout(sandwiches);
        sandwiches.setLayout(sandwichesLayout);
        sandwichesLayout.setHorizontalGroup(
            sandwichesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sandList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        sandwichesLayout.setVerticalGroup(
            sandwichesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sandList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(sandwiches, "card5");

        jList5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Spaghetti & Meatballs\t\t\t\t$10.99", " ", "Blackened Salmon\t\t\t\t$14.99", " ", "New York Strip\t\t\t\t\t$17.99", " ", "Ribeye\t\t\t\t\t$19.99", " ", "Fried Chicken\t\t\t\t\t$14.99", " ", "Charred Chicken Burrito\t\t\t\t$12.99", " ", "Lentil Marsala and Rice\t\t\t\t$9.99" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        entreeList.setViewportView(jList5);

        javax.swing.GroupLayout entreesLayout = new javax.swing.GroupLayout(entrees);
        entrees.setLayout(entreesLayout);
        entreesLayout.setHorizontalGroup(
            entreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entreeList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        entreesLayout.setVerticalGroup(
            entreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entreeList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(entrees, "card4");

        jList6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Molten Lava Cake\t\t\t\t$8.99", " ", "Cheesecake\t\t\t\t\t$6.99", " ", "Pie ala Mode\t\t\t\t\t$6.99", " ", "Espresso\t\t\t\t\t$2.99" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        dessertList.setViewportView(jList6);

        javax.swing.GroupLayout dessertsLayout = new javax.swing.GroupLayout(desserts);
        desserts.setLayout(dessertsLayout);
        dessertsLayout.setHorizontalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dessertList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        dessertsLayout.setVerticalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dessertList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(desserts, "card3");

        jList7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Domestic Beer Btl\t\t\t\t$3.99", " ", "Import Beer Btl\t\t\t\t\t$4.99", " ", "Draft Beer\t\t\t\t\t$5.00", " ", "Glass Wine\t\t\t\t\t$6.00", " ", "Fountain Soda\t\t\t\t\t$2.99", " ", "Iced Tea\t\t\t\t\t$2.99" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        drinkList.setViewportView(jList7);

        javax.swing.GroupLayout drinksLayout = new javax.swing.GroupLayout(drinks);
        drinks.setLayout(drinksLayout);
        drinksLayout.setHorizontalGroup(
            drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinkList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        drinksLayout.setVerticalGroup(
            drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinkList, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        dynamicPanel.add(drinks, "card2");

        jList8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jList8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "!PEANUT!", "!GLUTEN!", "!ONION!", "!GARLIC!", "!DAIRY!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList8);

        javax.swing.GroupLayout allergiesLayout = new javax.swing.GroupLayout(allergies);
        allergies.setLayout(allergiesLayout);
        allergiesLayout.setHorizontalGroup(
            allergiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        allergiesLayout.setVerticalGroup(
            allergiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        dynamicPanel.add(allergies, "card11");

        jList9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jList9.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "$Bacon", "$Extra Meat", "$Extra Side", "$Double" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList9);

        javax.swing.GroupLayout upchargeLayout = new javax.swing.GroupLayout(upcharge);
        upcharge.setLayout(upchargeLayout);
        upchargeLayout.setHorizontalGroup(
            upchargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        upchargeLayout.setVerticalGroup(
            upchargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        dynamicPanel.add(upcharge, "card10");

        jList10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No Cheese", "Rare", "Medium Rare", "Medium", "Medium Well", "Well", "No Onion", "No Tomato", "No Mayo", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList10);

        javax.swing.GroupLayout noUpchargeLayout = new javax.swing.GroupLayout(noUpcharge);
        noUpcharge.setLayout(noUpchargeLayout);
        noUpchargeLayout.setHorizontalGroup(
            noUpchargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        noUpchargeLayout.setVerticalGroup(
            noUpchargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        dynamicPanel.add(noUpcharge, "card9");

        Order.add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 690, 550));

        btnApps.setText("Appetizers");
        btnApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppsActionPerformed(evt);
            }
        });
        Order.add(btnApps, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 170, 50));

        btnSalad.setText("Salads");
        btnSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaladActionPerformed(evt);
            }
        });
        Order.add(btnSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 170, 50));

        btnSandwich.setText("Sandwiches");
        btnSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSandwichActionPerformed(evt);
            }
        });
        Order.add(btnSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 170, 50));

        btnEntree.setText("Entrees");
        btnEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntreeActionPerformed(evt);
            }
        });
        Order.add(btnEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 170, 50));

        btnDessert.setText("Desserts");
        btnDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDessertActionPerformed(evt);
            }
        });
        Order.add(btnDessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 170, 50));

        btnDrinks.setText("Drinks");
        btnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinksActionPerformed(evt);
            }
        });
        Order.add(btnDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 170, 50));

        btnAdd.setText("Add");
        Order.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 170, 50));

        btnPay.setText("Payment");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        Order.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 170, 50));

        btnSend.setText("Send/Exit");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        Order.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 170, 50));

        btnAddNoCharge.setText("Add");
        btnAddNoCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoChargeActionPerformed(evt);
            }
        });
        Order.add(btnAddNoCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 170, 60));

        btnAddCharge.setText("$Add");
        btnAddCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChargeActionPerformed(evt);
            }
        });
        Order.add(btnAddCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 170, 60));

        btnAllergy.setText("!ALLERGY!");
        btnAllergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllergyActionPerformed(evt);
            }
        });
        Order.add(btnAllergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 170, 60));

        btnVoid.setText("Void");
        Order.add(btnVoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 170, 50));

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        Order.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 170, 50));

        s1.setText("Seat 1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        Order.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        s2.setText("Seat 2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        Order.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        s3.setText("Seat 3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        Order.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        s4.setText("Seat 4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        Order.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        mainPanel.add(Order, "order");

        Tables.setPreferredSize(new java.awt.Dimension(1300, 750));
        Tables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl10.setText("10");
        tbl10.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl10ActionPerformed(evt);
            }
        });
        Tables.add(tbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 100, 100));

        tbl20.setText("20");
        tbl20.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl20ActionPerformed(evt);
            }
        });
        Tables.add(tbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 100));

        tbl30.setText("30");
        tbl30.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl30ActionPerformed(evt);
            }
        });
        Tables.add(tbl30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 110));

        tbl40.setText("40");
        tbl40.setToolTipText("");
        tbl40.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl40ActionPerformed(evt);
            }
        });
        Tables.add(tbl40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 110, 110));

        tbl50.setText("50");
        tbl50.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl50ActionPerformed(evt);
            }
        });
        Tables.add(tbl50, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 110, 110));

        tbl60.setText("60");
        tbl60.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl60ActionPerformed(evt);
            }
        });
        Tables.add(tbl60, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, 100));

        tbl61.setText("61");
        tbl61.setPreferredSize(new java.awt.Dimension(80, 30));
        tbl61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl61ActionPerformed(evt);
            }
        });
        Tables.add(tbl61, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 110, 110));

        newTable.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        newTable.setText("Exit");
        newTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTableActionPerformed(evt);
            }
        });
        Tables.add(newTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 140, 50));

        report.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        report.setText("Make Table");
        Tables.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 140, 50));

        exitTables.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        exitTables.setText("Run Report");
        Tables.add(exitTables, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 150, 140, 50));

        mainPanel.add(Tables, "tables");

        Payment.setPreferredSize(new java.awt.Dimension(1300, 750));
        Payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatPayment.setBackground(new java.awt.Color(204, 204, 204));
        seatPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        seatPayment.setLayout(new java.awt.CardLayout());
        Payment.add(seatPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 680, 420));

        Pay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pay.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emptyCashLayout = new javax.swing.GroupLayout(emptyCash);
        emptyCash.setLayout(emptyCashLayout);
        emptyCashLayout.setHorizontalGroup(
            emptyCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        emptyCashLayout.setVerticalGroup(
            emptyCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Pay.add(emptyCash, "card3");

        creditCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPayment.setText("Total Card Payment:");
        creditCard.add(cardPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 40));

        tipLabel.setText("Tip:");
        creditCard.add(tipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 40));
        creditCard.add(tipIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 230, 30));

        cardAccept.setText("Accept");
        creditCard.add(cardAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        cardCancel.setText("Cancel");
        creditCard.add(cardCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        creditCard.add(cardPayIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, 30));

        Pay.add(creditCard, "card4");

        payInCash.setPreferredSize(new java.awt.Dimension(676, 176));
        payInCash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPayment.setText("Total Cash Payment:");
        payInCash.add(totalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 40));

        changeDue.setText("Change Due:");
        payInCash.add(changeDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 40));
        payInCash.add(payIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 230, 30));

        accept.setText("Accept");
        payInCash.add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        cancel.setText("Cancel");
        payInCash.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        change.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        change.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        payInCash.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, 20));

        Pay.add(payInCash, "card2");

        Payment.add(Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 680, 180));

        btnCard.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCard.setText("Credit Card");
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });
        Payment.add(btnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 250, 90));

        btnCash.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        Payment.add(btnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 250, 90));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        Payment.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 250, 90));

        seat1.setText("Seat 1");
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });
        Payment.add(seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        seat2.setText("Seat 2");
        seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat2ActionPerformed(evt);
            }
        });
        Payment.add(seat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        seat3.setText("Seat 3");
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });
        Payment.add(seat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        seat4.setText("Seat 4");
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });
        Payment.add(seat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        allSeat.setText("All Seats");
        allSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSeatActionPerformed(evt);
            }
        });
        Payment.add(allSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        mainPanel.add(Payment, "payment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void disableButtons(){
        //disable the buttons on the order panel until a toggle button is enabled
        btnApps.setEnabled(false);
        btnSalad.setEnabled(false);
        btnSandwich.setEnabled(false);
        btnEntree.setEnabled(false);
        btnDrinks.setEnabled(false);
        btnDessert.setEnabled(false);
        btnAddNoCharge.setEnabled(false);
        btnAddCharge.setEnabled(false);
        btnAllergy.setEnabled(false);
    }
    
    private void enableButtons(){
        //enable the buttons on the order panel while a toggle button is enabled
        btnApps.setEnabled(true);
        btnSalad.setEnabled(true);
        btnSandwich.setEnabled(true);
        btnEntree.setEnabled(true);
        btnDrinks.setEnabled(true);
        btnDessert.setEnabled(true);
        btnAddNoCharge.setEnabled(true);
        btnAddCharge.setEnabled(true);
        btnAllergy.setEnabled(true);
    }
    
    private void tbl50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl50ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl50ActionPerformed

    private void btnEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntreeActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(entrees);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnEntreeActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        String takeText;
        takeText = input.getText() + btnOne.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        String takeText;
        takeText = input.getText() + btnTwo.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        String takeText;
        takeText = input.getText() + btnThree.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        String takeText;
        takeText = input.getText() + btnFour.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        String takeText;
        takeText = input.getText() + btnFive.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        String takeText;
        takeText = input.getText() + btnSix.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        String takeText;
        takeText = input.getText() + btnSeven.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        String takeText;
        takeText = input.getText() + btnEight.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        String takeText;
        takeText = input.getText() + btnNine.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        String takeText;
        takeText = input.getText() + btnZero.getText();
        input.setText(takeText);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        input.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        String inputID;                                         //insantiate an empty string
        boolean isAuthorized = false;                           //this boolean will tell us if the user is authorized
        inputID = input.getText();                              //get the text from the text box
        double inputIDNum = Double.parseDouble(inputID);        //parse it to a double
        
        for(int i = 0; i < ids.length; i++){                    //iterate through the array of ID numbers
            if(inputIDNum == ids[i]){                           //if the entered ID number matches the current element in the array 
                isAuthorized = true;                            //set to true
            }    
        }
        if(isAuthorized){                                       //if boolean is true
            mainPanel.removeAll();                              //move to the tables JPanel
            mainPanel.add(Tables);                              
            mainPanel.repaint();
            mainPanel.revalidate();
        }
        else{
            input.setText("");                                  //empty input text field
        }
        
        disableButtons();                                       //call method to disable order buttons
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void tbl40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl40ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl40ActionPerformed

    private void tbl30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl30ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl30ActionPerformed

    private void tbl20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl20ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl20ActionPerformed

    private void tbl10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl10ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl10ActionPerformed

    private void tbl60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl60ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl60ActionPerformed

    private void tbl61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl61ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Order);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tbl61ActionPerformed

    private void newTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTableActionPerformed
        mainPanel.removeAll();
        mainPanel.add(login);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        dynamicPanel.removeAll();
        dynamicPanel.add(orderPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_newTableActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Payment);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        mainPanel.removeAll();
        mainPanel.add(login);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        Pay.removeAll();
        Pay.add(emptyCash);
        Pay.repaint();
        Pay.revalidate();
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        Pay.removeAll();
        Pay.add(payInCash);
        Pay.repaint();
        Pay.revalidate();
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppsActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(appetizers);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnAppsActionPerformed

    private void btnSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaladActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(salads);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnSaladActionPerformed

    private void btnSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSandwichActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(sandwiches);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnSandwichActionPerformed

    private void btnDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDessertActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(desserts);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnDessertActionPerformed

    private void btnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinksActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(drinks);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnDrinksActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(orderPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        Pay.removeAll();
        Pay.add(creditCard);
        Pay.repaint();
        Pay.revalidate();
    }//GEN-LAST:event_btnCardActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        //let buttons be enabled when toggle button is pushed, and disable when it is no longer selected
        if(s1.isSelected()){
            enableButtons();                        //enable menu buttons
            //disable other toggle buttons
            s2.setEnabled(false);
            s3.setEnabled(false);
            s4.setEnabled(false);
        }
        else{
            disableButtons();                       //disable menu buttons
            //enable other toggle buttons
            s2.setEnabled(true);
            s3.setEnabled(true);
            s4.setEnabled(true);
        }
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        //let buttons be enabled when toggle button is pushed, and disable when it is no longer selected
        if(s2.isSelected()){
            enableButtons();                        //enable menu buttons
            //disable other toggle buttons
            s1.setEnabled(false);
            s3.setEnabled(false);
            s4.setEnabled(false);
        }
        else{
            disableButtons();                       //disable menu buttons
            //enable other toggle buttons
            s1.setEnabled(true);
            s3.setEnabled(true);
            s4.setEnabled(true);
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        //let buttons be enabled when toggle button is pushed, and disable when it is no longer selected
        if(s3.isSelected()){
            enableButtons();                        //enable menu buttons
            //disable other toggle buttons
            s1.setEnabled(false);
            s2.setEnabled(false);
            s4.setEnabled(false);
        }
        else{
            disableButtons();                       //disable menu buttons
            //enable other toggle buttons
            s1.setEnabled(true);
            s2.setEnabled(true);
            s4.setEnabled(true);
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        //let buttons be enabled when toggle button is pushed, and disable when it is no longer selected
        if(s4.isSelected()){
            enableButtons();                        //enable menu buttons
            //disable other toggle buttons
            s1.setEnabled(false);
            s2.setEnabled(false);
            s3.setEnabled(false);
        }
        else{
            disableButtons();                       //disable menu buttons
            //enable other toggle buttons
            s1.setEnabled(true);
            s2.setEnabled(true);
            s3.setEnabled(true);
        }
    }//GEN-LAST:event_s4ActionPerformed

    private void btnAddNoChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoChargeActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(noUpcharge);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnAddNoChargeActionPerformed

    private void btnAddChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChargeActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(upcharge);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnAddChargeActionPerformed

    private void btnAllergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllergyActionPerformed
        dynamicPanel.removeAll();
        dynamicPanel.add(allergies);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnAllergyActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        mainPanel.removeAll();
        mainPanel.add(Tables);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        dynamicPanel.removeAll();
        dynamicPanel.add(orderPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_btnSendActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed

        if(seat1.isSelected()){
            allSeat.setEnabled(false);
        }
        else{
            allSeat.setEnabled(true);
        }
    }//GEN-LAST:event_seat1ActionPerformed

    private void seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat2ActionPerformed
        if(seat2.isSelected()){
            allSeat.setEnabled(false);
        }
        else{
            allSeat.setEnabled(true);
        }
    }//GEN-LAST:event_seat2ActionPerformed

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
        if(seat3.isSelected()){
            allSeat.setEnabled(false);
        }
        else{
            allSeat.setEnabled(true);
        }
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        if(seat4.isSelected()){
            allSeat.setEnabled(false);
        }
        else{
            allSeat.setEnabled(true);
        }
    }//GEN-LAST:event_seat4ActionPerformed

    private void allSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSeatActionPerformed
        if(allSeat.isSelected()){
            seat1.setEnabled(false);
            seat2.setEnabled(false);
            seat3.setEnabled(false);
            seat4.setEnabled(false);
        }
        else{
            seat1.setEnabled(true);
            seat2.setEnabled(true);
            seat3.setEnabled(true);
            seat4.setEnabled(true);
        }
    }//GEN-LAST:event_allSeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Pay;
    private javax.swing.JPanel Payment;
    private javax.swing.JPanel Tables;
    private javax.swing.JButton accept;
    private javax.swing.JToggleButton allSeat;
    private javax.swing.JPanel allergies;
    private javax.swing.JScrollPane appList;
    private javax.swing.JPanel appetizers;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCharge;
    private javax.swing.JButton btnAddNoCharge;
    private javax.swing.JButton btnAllergy;
    private javax.swing.JButton btnApps;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnDessert;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEntree;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSalad;
    private javax.swing.JButton btnSandwich;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnVoid;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cardAccept;
    private javax.swing.JButton cardCancel;
    private javax.swing.JTextField cardPayIn;
    private javax.swing.JLabel cardPayment;
    private javax.swing.JLabel change;
    private javax.swing.JLabel changeDue;
    private javax.swing.JPanel creditCard;
    private javax.swing.JScrollPane currentOrder;
    private javax.swing.JScrollPane dessertList;
    private javax.swing.JPanel desserts;
    private javax.swing.JScrollPane drinkList;
    private javax.swing.JPanel drinks;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JPanel emptyCash;
    private javax.swing.JScrollPane entreeList;
    private javax.swing.JPanel entrees;
    private javax.swing.JButton exitTables;
    private javax.swing.JTextField input;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel login;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newTable;
    private javax.swing.JPanel noUpcharge;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JTextField payIn;
    private javax.swing.JPanel payInCash;
    private javax.swing.JButton report;
    private javax.swing.JToggleButton s1;
    private javax.swing.JToggleButton s2;
    private javax.swing.JToggleButton s3;
    private javax.swing.JToggleButton s4;
    private javax.swing.JScrollPane saladList;
    private javax.swing.JPanel salads;
    private javax.swing.JScrollPane sandList;
    private javax.swing.JPanel sandwiches;
    private javax.swing.JToggleButton seat1;
    private javax.swing.JToggleButton seat2;
    private javax.swing.JToggleButton seat3;
    private javax.swing.JToggleButton seat4;
    private javax.swing.JPanel seatPayment;
    private javax.swing.JButton tbl10;
    private javax.swing.JButton tbl20;
    private javax.swing.JButton tbl30;
    private javax.swing.JButton tbl40;
    private javax.swing.JButton tbl50;
    private javax.swing.JButton tbl60;
    private javax.swing.JButton tbl61;
    private javax.swing.JTextField tipIn;
    private javax.swing.JLabel tipLabel;
    private javax.swing.JLabel totalPayment;
    private javax.swing.JPanel upcharge;
    // End of variables declaration//GEN-END:variables
}
